version: "3.9"
services:
  apache:
    build: ./web-server
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - ldap
    volumes:
      - ./certificados/restaurante.work.gd.cer:/etc/ssl/certs/restaurante.work.gd.cer:ro
      - ./certificados/restaurante.work.gd.key:/etc/ssl/private/restaurante.work.gd.key:ro
    environment:
      LDAP_SERVER: ldap

  ldap:
    build: ./ldap-server
    ports:
      - "389:389" 
      - "636:636" 
    environment:
      LDAP_DOMAIN: "restaurante.local"
      LDAP_ORGANISATION: "Restaurante Ejemplo"
      LDAP_ADMIN_PASSWORD: "adminpassword"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d

volumes:
  ldap_data:
  ldap_config: